document.write("<img src=\"headshot.jpg\" width=\"240px\"></img>  ");
document.write("<br />                                                                                                ");
document.write("<p>                                                                                                   ");
document.write("319 Vance Hall<br />                                                               ");
document.write("3733 Spruce St.<br />                                                                                ");
document.write("Philadelphia, PA 19104                                                                                ");
document.write("<br />                                                                                                ");
document.write("<br />                                                                                                ");
document.write("<a class=\"email\" href=\"mailto:claytonf@wharton.upenn.edu\">claytonf@wharton.upenn.edu</a><br />    ");
document.write("(214) 673-2800 <br />                                                                                 ");
document.write("                                                                                                      ");
document.write("</p>                                                                                                  ");
