document.write("<img src=\"headshot.jpg\" width=\"240px\"></img>  ");
document.write("<br />                                            ");
document.write("<p>                                               ");
document.write("Baylor University<br />                           ");
document.write("Hankamer School of Business<br />                 ");
document.write("Department of Economics<br />                     ");
document.write("Foster 320.14                                     ");
document.write("<br />                                            ");
document.write("<br />                                            ");
document.write("clayton_featherstone@baylor.edu<br />             ");
document.write("                                                  ");
document.write("</p>                                              ");
